import { StyleSheet } from 'react-native';
import { MD3Theme } from 'react-native-paper';

export const createHomeStyles = (theme: MD3Theme) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: theme.colors.background },
    container: { padding: 16, paddingBottom: 24 },
    summaryCard: {
      borderRadius: 28,
      backgroundColor: theme.colors.surfaceVariant,
      marginBottom: 14,
    },
    summaryLabel: { color: theme.colors.onSurfaceVariant, marginBottom: 8 },
    balanceText: { fontWeight: '700', color: theme.colors.onSurface, marginBottom: 14 },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 10,
    },
    summaryItem: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
    summaryItemLabel: { color: theme.colors.onSurfaceVariant, fontWeight: '700' },
    summaryIn: { color: theme.colors.primary, fontWeight: '700' },
    summaryOut: { color: theme.colors.error, fontWeight: '700' },
    incomeAvatar: { backgroundColor: theme.colors.primaryContainer },
    expenseAvatar: { backgroundColor: theme.colors.errorContainer },
    actionRow: { flexDirection: 'row', gap: 10, marginBottom: 18 },
    incomeButton: {
      flex: 1,
      borderRadius: 14,
      backgroundColor: theme.colors.primary,
      shadowColor: theme.colors.primary,
      shadowOpacity: 0.25,
      shadowRadius: 10,
    },
    expenseButton: {
      flex: 1,
      borderRadius: 14,
      borderColor: theme.colors.error,
      backgroundColor: theme.colors.error,
    },
    bigButtonContent: { height: 64 },
    bigButtonLabel: { fontSize: 16, fontWeight: '700' },
    expenseButtonLabel: { fontSize: 16, fontWeight: '700', color: theme.colors.onError },
    historyHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    historyTitle: { color: theme.colors.onSurface, fontWeight: '700' },
    groupBlock: { marginBottom: 14 },
    groupTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    groupTitle: { color: theme.colors.onSurfaceVariant, fontWeight: '700', marginRight: 8 },
    groupDivider: { flex: 1, backgroundColor: theme.colors.outlineVariant },
    transactionCard: {
      borderRadius: 24,
      backgroundColor: theme.colors.surface,
      marginBottom: 10,
    },
    transactionContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    leftInfo: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 12 },
    transactionTextWrap: { flexShrink: 1 },
    transactionTitle: { color: theme.colors.onSurface, fontWeight: '700' },
    transactionMeta: { color: theme.colors.onSurfaceVariant, marginTop: 2 },
    rightInfo: { display: 'flex', alignItems: 'flex-end' },
    transactionAmount: { fontWeight: '700' },
    amountIn: { color: theme.colors.primary },
    amountOut: { color: theme.colors.onSurface },
    dialog: { backgroundColor: theme.colors.surface },
    searchbar: { marginBottom: 8 },
    selectedCategoryText: { marginBottom: 10, color: theme.colors.onSurfaceVariant },
    expenseDateInput: { marginTop: 10 },
  });
