import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#f6f8fb' },
  container: { padding: 16, paddingBottom: 24 },
  summaryCard: {
    borderRadius: 28,
    backgroundColor: '#f1f3f6',
    marginBottom: 14,
  },
  summaryLabel: { color: '#65778f', marginBottom: 8 },
  balanceText: { fontWeight: '700', color: '#09122d', marginBottom: 14 },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  summaryItem: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  summaryItemLabel: { color: '#8f9cb1', fontWeight: '700' },
  summaryIn: { color: '#0da837', fontWeight: '700' },
  summaryOut: { color: '#ef3d5b', fontWeight: '700' },
  incomeAvatar: { backgroundColor: '#d9f7ea' },
  expenseAvatar: { backgroundColor: '#ffe5ea' },
  actionRow: { flexDirection: 'row', gap: 10, marginBottom: 18 },
  incomeButton: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: '#0da837',
    shadowColor: '#0da837',
    shadowOpacity: 0.25,
    shadowRadius: 10,
  },
  expenseButton: {
    flex: 1,
    borderRadius: 14,
    borderColor: '#dd314d',
    backgroundColor: '#ef3d5b',
  },
  bigButtonContent: { height: 64 },
  bigButtonLabel: { fontSize: 16, fontWeight: '700' },
  expenseButtonLabel: { fontSize: 16, fontWeight: '700', color: '#fff' },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  historyTitle: { color: '#09122d', fontWeight: '700' },
  groupBlock: { marginBottom: 14 },
  groupTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  groupTitle: { color: '#8f9cb1', fontWeight: '700', marginRight: 8 },
  groupDivider: { flex: 1, backgroundColor: '#dde3ec' },
  transactionCard: {
    borderRadius: 24,
    backgroundColor: '#ffffff',
    marginBottom: 10,
  },
  transactionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  leftInfo: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 12 },
  transactionTextWrap: { flexShrink: 1 },
  transactionTitle: { color: '#111729', fontWeight: '700' },
  transactionMeta: { color: '#8f9cb1', marginTop: 2 },
  transactionAmount: { fontWeight: '700' },
  amountIn: { color: '#0f9f65' },
  amountOut: { color: '#111729' },
  dialog: { backgroundColor: '#fff' },
  searchbar: { marginBottom: 8 },
  selectedCategoryText: { marginBottom: 10, color: '#455a64' },
  expenseDateInput: { marginTop: 10 },
});
